<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentGate.Domain\PaymentGate.Domain.csproj" />
    <ProjectReference Include="..\PaymentGateway.Persistence\PaymentGateway.Persistence.csproj" />
  </ItemGroup>

</Project>
