<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>688068e2-7c3d-48c8-af03-5c2121a10728</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentGate.Application\PaymentGate.Application.csproj" />
    <ProjectReference Include="..\PaymentGate.Domain\PaymentGate.Domain.csproj" />
    <ProjectReference Include="..\PaymentGateway.Persistence\PaymentGateway.Persistence.csproj" />
    <ProjectReference Include="..\Paystack\Paystack.csproj" />
  </ItemGroup>

</Project>
